FROM apache/airflow:3.1.8

# Switch to root to install system-level dependencies
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    libgomp1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Switch back to the standard airflow user
USER airflow

# Copy your requirements file and install the data science libraries
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt