stages:
  preprocess:
    cmd: python src/data_processing.py
    deps:
    - data/raw_data/household_power_consumption.txt
    - src/data_processing.py
    outs:
    - data/processed/train.csv
    
  train:
    cmd: python src/train.py
    deps:
    - data/processed/live_data.csv
    - data/processed/train.csv
    - src/train.py
    params:
    - features
    - model
    outs:
    - model/xgb_model.pkl
    metrics:
    - model/metrics.json
