stages:
  preprocess:
    cmd: python src/data_processing.py
    deps:
    - data/raw_data/household_power_consumption.txt
    - src/data_processing.py
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
