{
 "title": "vis",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "NODE EXPORTER HEALTH",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Back End Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi-backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE vs TIME",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL INFERENCE COUNT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_predictions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MEAN ABSOLUTE ERROR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "model_mae", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WEEK FORECASt INFERENCE TIME",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(model_forecast_time_seconds_sum[5m]) / rate(model_forecast_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROOT MEANS SQUARED ERROR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "model_rmse", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MODEL INFERENCE TIME ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(model_inference_time_seconds_sum[5m]) / rate(model_inference_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}